"""integration schema and realtime notify

Revision ID: fc49598d464b
Revises: ddd07e040ac9
Create Date: 2026-08-27 22:49:12.096704
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "fc49598d464b"
down_revision: str | None = "ddd07e040ac9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amocrm_connections",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "connected",
                "disconnected",
                name="amoconnectionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("account_domain", sa.String(length=255), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=True),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("redirect_uri", sa.String(length=2048), nullable=False),
        sa.Column("encrypted_client_secret", sa.LargeBinary(), nullable=True),
        sa.Column("encrypted_access_token", sa.LargeBinary(), nullable=True),
        sa.Column("encrypted_refresh_token", sa.LargeBinary(), nullable=True),
        sa.Column("credentials_key_id", sa.String(length=100), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_amocrm_connections_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amocrm_connections")),
        sa.UniqueConstraint("workspace_id", name="uq_amocrm_connection_workspace"),
    )
    op.create_index(
        "ix_amocrm_connections_account_domain",
        "amocrm_connections",
        ["account_domain"],
        unique=False,
    )
    op.create_table(
        "amocrm_oauth_states",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("initiated_by_id", sa.Uuid(), nullable=False),
        sa.Column("state_digest", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("redirect_uri", sa.String(length=2048), nullable=False),
        sa.Column("encrypted_client_secret", sa.LargeBinary(), nullable=False),
        sa.Column("credentials_key_id", sa.String(length=100), nullable=False),
        sa.Column(
            "allowed_referers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by_id"],
            ["users.id"],
            name=op.f("fk_amocrm_oauth_states_initiated_by_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_amocrm_oauth_states_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amocrm_oauth_states")),
        sa.UniqueConstraint("state_digest", name="uq_amocrm_oauth_state_digest"),
    )
    op.create_index(
        "ix_amocrm_oauth_states_initiated_by_id",
        "amocrm_oauth_states",
        ["initiated_by_id"],
        unique=False,
    )
    op.create_index(
        "ix_amocrm_oauth_states_workspace_expiry",
        "amocrm_oauth_states",
        ["workspace_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "import_jobs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "paused",
                "succeeded",
                "failed",
                name="importstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column(
            "cursor",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "user_mapping",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "counts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("report_object_key", sa.String(length=1024), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_import_jobs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
    )
    op.create_index(
        "ix_import_jobs_workspace_status_updated",
        "import_jobs",
        ["workspace_id", "status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "notification_templates",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("subject_template", sa.String(length=998), nullable=True),
        sa.Column("body_template", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_notification_templates_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_templates")),
        sa.UniqueConstraint(
            "workspace_id", "name", "channel", name="uq_notification_template_name_channel"
        ),
    )
    op.create_index(
        op.f("ix_notification_templates_workspace_id"),
        "notification_templates",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "external_entity_maps",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("import_job_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("internal_id", sa.Uuid(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
            name=op.f("fk_external_entity_maps_import_job_id_import_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_external_entity_maps_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_entity_maps")),
        sa.UniqueConstraint(
            "workspace_id",
            "provider",
            "entity_type",
            "external_id",
            name="uq_external_entity_provider_id",
        ),
    )
    op.create_index(
        "ix_external_entity_maps_import_job_id",
        "external_entity_maps",
        ["import_job_id"],
        unique=False,
    )
    op.create_index(
        "ix_external_entity_maps_internal",
        "external_entity_maps",
        ["workspace_id", "entity_type", "internal_id"],
        unique=False,
    )
    op.create_table(
        "channel_connections",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "email",
                "telegram",
                "max",
                "internal",
                name="channelkind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum("disabled", "active", "degraded", name="connectionstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("encrypted_credentials", sa.LargeBinary(), nullable=True),
        sa.Column("credentials_key_id", sa.String(length=100), nullable=True),
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("default_pipeline_id", sa.Uuid(), nullable=True),
        sa.Column("default_stage_id", sa.Uuid(), nullable=True),
        sa.Column("default_assignee_id", sa.Uuid(), nullable=True),
        sa.Column("last_healthcheck_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["default_assignee_id"],
            ["users.id"],
            name=op.f("fk_channel_connections_default_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["default_pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_channel_connections_default_pipeline_id_pipelines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["default_stage_id"],
            ["stages.id"],
            name=op.f("fk_channel_connections_default_stage_id_stages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_channel_connections_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_connections")),
        sa.UniqueConstraint(
            "workspace_id", "kind", "name", name="uq_channel_connection_workspace_kind_name"
        ),
    )
    op.create_index(
        "ix_channel_connections_default_assignee_id",
        "channel_connections",
        ["default_assignee_id"],
        unique=False,
    )
    op.create_index(
        "ix_channel_connections_default_pipeline_id",
        "channel_connections",
        ["default_pipeline_id"],
        unique=False,
    )
    op.create_index(
        "ix_channel_connections_default_stage_id",
        "channel_connections",
        ["default_stage_id"],
        unique=False,
    )
    op.create_index(
        "ix_channel_connections_workspace_kind_status",
        "channel_connections",
        ["workspace_id", "kind", "status"],
        unique=False,
    )
    op.create_table(
        "contact_channel_consents",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("address", sa.String(length=512), nullable=False),
        sa.Column("normalized_address", sa.String(length=512), nullable=False),
        sa.Column("purpose", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("granted", "revoked", name="consentstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_contact_channel_consents_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_contact_channel_consents_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_channel_consents")),
        sa.UniqueConstraint(
            "contact_id",
            "channel",
            "normalized_address",
            "purpose",
            name="uq_contact_consent_channel_address_purpose",
        ),
    )
    op.create_index(
        "ix_contact_consents_contact_id", "contact_channel_consents", ["contact_id"], unique=False
    )
    op.create_index(
        "ix_contact_consents_workspace_status",
        "contact_channel_consents",
        ["workspace_id", "status", "channel"],
        unique=False,
    )
    op.create_table(
        "contact_points",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("email", "phone", name="contactpointkind", native_enum=False),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("normalized_value", sa.String(length=512), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_contact_points_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_contact_points_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_points")),
        sa.UniqueConstraint(
            "contact_id", "kind", "normalized_value", name="uq_contact_point_value"
        ),
    )
    op.create_index("ix_contact_points_contact_id", "contact_points", ["contact_id"], unique=False)
    op.create_index(
        "ix_contact_points_workspace_kind_normalized",
        "contact_points",
        ["workspace_id", "kind", "normalized_value"],
        unique=False,
    )
    op.create_table(
        "forms",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column(
            "fields_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "allowed_origins",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("honeypot_field", sa.String(length=100), nullable=False),
        sa.Column("success_message", sa.String(length=500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_forms_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_forms_pipeline_id_pipelines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_forms_source_id_sources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"], ["stages.id"], name=op.f("fk_forms_stage_id_stages"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_forms_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forms")),
        sa.UniqueConstraint("slug", name="uq_form_public_slug"),
    )
    op.create_index("ix_forms_assignee_id", "forms", ["assignee_id"], unique=False)
    op.create_index("ix_forms_pipeline_id", "forms", ["pipeline_id"], unique=False)
    op.create_index("ix_forms_slug_active", "forms", ["slug", "is_active"], unique=False)
    op.create_index("ix_forms_source_id", "forms", ["source_id"], unique=False)
    op.create_index("ix_forms_stage_id", "forms", ["stage_id"], unique=False)
    op.create_table(
        "notification_rules",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "audience",
            sa.Enum("employee", "client", name="notificationaudience", native_enum=False),
            nullable=False,
        ),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("pipeline_id", sa.Uuid(), nullable=True),
        sa.Column("stage_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column(
            "filters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "recipients",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("delay_seconds", sa.Integer(), nullable=False),
        sa.Column("require_client_consent", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delay_seconds >= 0", name=op.f("ck_notification_rules_notification_delay_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_notification_rules_pipeline_id_pipelines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_notification_rules_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stages.id"],
            name=op.f("fk_notification_rules_stage_id_stages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["notification_templates.id"],
            name=op.f("fk_notification_rules_template_id_notification_templates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_notification_rules_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_rules")),
    )
    op.create_index(
        "ix_notification_rules_pipeline_id", "notification_rules", ["pipeline_id"], unique=False
    )
    op.create_index(
        "ix_notification_rules_source_id", "notification_rules", ["source_id"], unique=False
    )
    op.create_index(
        "ix_notification_rules_stage_id", "notification_rules", ["stage_id"], unique=False
    )
    op.create_index(
        "ix_notification_rules_template_id", "notification_rules", ["template_id"], unique=False
    )
    op.create_index(
        "ix_notification_rules_workspace_event_enabled",
        "notification_rules",
        ["workspace_id", "event_type", "is_enabled"],
        unique=False,
    )
    op.create_table(
        "webhook_endpoints",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("encrypted_secret", sa.LargeBinary(), nullable=False),
        sa.Column("secret_key_id", sa.String(length=100), nullable=True),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_webhook_endpoints_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_webhook_endpoints_pipeline_id_pipelines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_webhook_endpoints_source_id_sources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stages.id"],
            name=op.f("fk_webhook_endpoints_stage_id_stages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_webhook_endpoints_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_endpoints")),
        sa.UniqueConstraint("slug", name="uq_webhook_endpoint_public_slug"),
    )
    op.create_index(
        "ix_webhook_endpoints_assignee_id", "webhook_endpoints", ["assignee_id"], unique=False
    )
    op.create_index(
        "ix_webhook_endpoints_pipeline_id", "webhook_endpoints", ["pipeline_id"], unique=False
    )
    op.create_index(
        "ix_webhook_endpoints_slug_active", "webhook_endpoints", ["slug", "is_active"], unique=False
    )
    op.create_index(
        "ix_webhook_endpoints_source_id", "webhook_endpoints", ["source_id"], unique=False
    )
    op.create_index(
        "ix_webhook_endpoints_stage_id", "webhook_endpoints", ["stage_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("channel_connection_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("deal_id", sa.Uuid(), nullable=True),
        sa.Column("external_thread_id", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "closed", "review_needed", name="conversationstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "participant",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_connection_id"],
            ["channel_connections.id"],
            name=op.f("fk_conversations_channel_connection_id_channel_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_conversations_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.id"],
            name=op.f("fk_conversations_deal_id_deals"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_conversations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint(
            "channel_connection_id",
            "external_thread_id",
            name="uq_conversation_connection_external_thread",
        ),
    )
    op.create_index(
        "ix_conversations_channel_connection_id",
        "conversations",
        ["channel_connection_id"],
        unique=False,
    )
    op.create_index("ix_conversations_contact_id", "conversations", ["contact_id"], unique=False)
    op.create_index("ix_conversations_deal_id", "conversations", ["deal_id"], unique=False)
    op.create_index(
        "ix_conversations_workspace_status_updated",
        "conversations",
        ["workspace_id", "status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "external_identities",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("channel_connection_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("connection_scope", sa.String(length=64), nullable=False),
        sa.Column("external_user_id", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=240), nullable=True),
        sa.Column(
            "profile",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_connection_id"],
            ["channel_connections.id"],
            name=op.f("fk_external_identities_channel_connection_id_channel_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_external_identities_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_external_identities_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_identities")),
        sa.UniqueConstraint(
            "workspace_id",
            "provider",
            "connection_scope",
            "external_user_id",
            name="uq_external_identity_provider_user",
        ),
    )
    op.create_index(
        "ix_external_identities_channel_connection_id",
        "external_identities",
        ["channel_connection_id"],
        unique=False,
    )
    op.create_index(
        "ix_external_identities_contact_id", "external_identities", ["contact_id"], unique=False
    )
    op.create_table(
        "form_rate_limit_buckets",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("subject_hash", sa.String(length=64), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["forms.id"],
            name=op.f("fk_form_rate_limit_buckets_form_id_forms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_form_rate_limit_buckets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_rate_limit_buckets")),
        sa.UniqueConstraint(
            "form_id",
            "subject_hash",
            "window_started_at",
            name="uq_form_rate_bucket_subject_window",
        ),
    )
    op.create_index(
        "ix_form_rate_bucket_expires", "form_rate_limit_buckets", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_form_rate_bucket_workspace_id",
        "form_rate_limit_buckets",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_form_rate_limit_buckets_form_id"),
        "form_rate_limit_buckets",
        ["form_id"],
        unique=False,
    )
    op.create_table(
        "form_submissions",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "accepted",
                "processing",
                "processed",
                "failed",
                name="formsubmissionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["forms.id"],
            name=op.f("fk_form_submissions_form_id_forms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_form_submissions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_submissions")),
        sa.UniqueConstraint("form_id", "idempotency_key", name="uq_form_submission_idempotency"),
    )
    op.create_index("ix_form_submissions_form_id", "form_submissions", ["form_id"], unique=False)
    op.create_index(
        "ix_form_submissions_workspace_status_created",
        "form_submissions",
        ["workspace_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "inbound_events",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("channel_connection_id", sa.Uuid(), nullable=True),
        sa.Column("source_key", sa.String(length=255), nullable=False),
        sa.Column("external_event_id", sa.String(length=512), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "accepted",
                "processing",
                "processed",
                "failed",
                name="inboundstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["channel_connection_id"],
            ["channel_connections.id"],
            name=op.f("fk_inbound_events_channel_connection_id_channel_connections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_inbound_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbound_events")),
        sa.UniqueConstraint(
            "workspace_id", "source_key", "external_event_id", name="uq_inbound_event_external_id"
        ),
        sa.UniqueConstraint(
            "workspace_id", "source_key", "idempotency_key", name="uq_inbound_event_idempotency_key"
        ),
    )
    op.create_index(
        "ix_inbound_events_channel_connection_id",
        "inbound_events",
        ["channel_connection_id"],
        unique=False,
    )
    op.create_index(
        "ix_inbound_events_workspace_status_received",
        "inbound_events",
        ["workspace_id", "status", "received_at"],
        unique=False,
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column(
            "audience",
            sa.Enum("employee", "client", name="notificationaudience", native_enum=False),
            nullable=False,
        ),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("recipient_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_address", sa.String(length=512), nullable=False),
        sa.Column("subject", sa.String(length=998), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "delivered",
                "failed",
                name="deliverystatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("provider_message_id", sa.String(length=512), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["notification_rules.id"],
            name=op.f("fk_notification_deliveries_rule_id_notification_rules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["notification_templates.id"],
            name=op.f("fk_notification_deliveries_template_id_notification_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_notification_deliveries_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
        sa.UniqueConstraint("workspace_id", "dedupe_key", name="uq_notification_delivery_dedupe"),
    )
    op.create_index(
        "ix_notification_deliveries_rule_id", "notification_deliveries", ["rule_id"], unique=False
    )
    op.create_index(
        "ix_notification_deliveries_template_id",
        "notification_deliveries",
        ["template_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_deliveries_workspace_status_scheduled",
        "notification_deliveries",
        ["workspace_id", "status", "scheduled_at"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("reply_to_id", sa.Uuid(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum("inbound", "outbound", name="messagedirection", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received", "queued", "sent", "failed", name="messagestatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("provider_message_id", sa.String(length=512), nullable=True),
        sa.Column("sender_external_id", sa.String(length=512), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_id"],
            ["messages.id"],
            name=op.f("fk_messages_reply_to_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_messages_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "conversation_id", "provider_message_id", name="uq_message_conversation_provider_id"
        ),
    )
    op.create_index(
        "ix_messages_outbound_pending",
        "messages",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("direction = 'outbound' AND status = 'queued'"),
    )
    op.create_index("ix_messages_reply_to_id", "messages", ["reply_to_id"], unique=False)
    op.create_index(
        "ix_messages_workspace_conversation_created",
        "messages",
        ["workspace_id", "conversation_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "purchase_schedules",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("assignee_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("remind_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "completed", "cancelled", name="purchaseschedulestatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("reminder_enqueued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_purchase_schedules_assignee_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_purchase_schedules_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["deal_id"],
            ["deals.id"],
            name=op.f("fk_purchase_schedules_deal_id_deals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_purchase_schedules_task_id_tasks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_purchase_schedules_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_schedules")),
        sa.UniqueConstraint("task_id", name="uq_purchase_schedule_task"),
        sa.UniqueConstraint(
            "workspace_id", "deal_id", "scheduled_for", name="uq_purchase_schedule_deal_occurrence"
        ),
    )
    op.create_index(
        "ix_purchase_schedules_assignee_id", "purchase_schedules", ["assignee_id"], unique=False
    )
    op.create_index(
        "ix_purchase_schedules_contact_id", "purchase_schedules", ["contact_id"], unique=False
    )
    op.create_index(
        "ix_purchase_schedules_workspace_status_scheduled",
        "purchase_schedules",
        ["workspace_id", "status", "scheduled_for"],
        unique=False,
    )
    op.create_table(
        "attachments",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_attachments_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_attachments_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
        sa.UniqueConstraint("object_key", name="uq_attachment_object_key"),
    )
    op.create_index(
        "ix_attachments_workspace_message",
        "attachments",
        ["workspace_id", "message_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_event_markers",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("occurrence_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_scheduled_event_markers_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_event_markers")),
        sa.UniqueConstraint(
            "workspace_id",
            "event_type",
            "entity_type",
            "entity_id",
            "occurrence_at",
            name="uq_scheduled_event_occurrence",
        ),
    )
    op.create_index(
        "ix_scheduled_event_lookup",
        "scheduled_event_markers",
        ["workspace_id", "event_type", "occurrence_at"],
        unique=False,
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            sa.text(
                """
                CREATE INDEX ix_contacts_fulltext
                ON contacts USING gin (
                    to_tsvector(
                        'simple',
                        coalesce(first_name, '') || ' ' ||
                        coalesce(last_name, '') || ' ' ||
                        coalesce(primary_email, '') || ' ' ||
                        coalesce(primary_phone, '')
                    )
                )
                """
            )
        )
        op.execute(
            sa.text(
                """
                CREATE INDEX ix_deals_fulltext
                ON deals USING gin (to_tsvector('simple', coalesce(title, '')))
                """
            )
        )
        op.execute(
            sa.text(
                """
                CREATE FUNCTION pulse_notify_realtime_event()
                RETURNS trigger AS $$
                BEGIN
                    PERFORM pg_notify('pulse_realtime', NEW.id::text);
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql
                """
            )
        )
        op.execute(
            sa.text(
                """
                CREATE TRIGGER trg_realtime_event_notify
                AFTER INSERT ON realtime_events
                FOR EACH ROW EXECUTE FUNCTION pulse_notify_realtime_event()
                """
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("DROP TRIGGER IF EXISTS trg_realtime_event_notify ON realtime_events"))
        op.execute(sa.text("DROP FUNCTION IF EXISTS pulse_notify_realtime_event()"))
        op.execute(sa.text("DROP INDEX IF EXISTS ix_deals_fulltext"))
        op.execute(sa.text("DROP INDEX IF EXISTS ix_contacts_fulltext"))
    op.drop_index("ix_scheduled_event_lookup", table_name="scheduled_event_markers")
    op.drop_table("scheduled_event_markers")
    op.drop_index("ix_attachments_workspace_message", table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(
        "ix_purchase_schedules_workspace_status_scheduled", table_name="purchase_schedules"
    )
    op.drop_index("ix_purchase_schedules_contact_id", table_name="purchase_schedules")
    op.drop_index("ix_purchase_schedules_assignee_id", table_name="purchase_schedules")
    op.drop_table("purchase_schedules")
    op.drop_index("ix_messages_workspace_conversation_created", table_name="messages")
    op.drop_index("ix_messages_reply_to_id", table_name="messages")
    op.drop_index(
        "ix_messages_outbound_pending",
        table_name="messages",
        postgresql_where=sa.text("direction = 'outbound' AND status = 'queued'"),
    )
    op.drop_table("messages")
    op.drop_index(
        "ix_notification_deliveries_workspace_status_scheduled",
        table_name="notification_deliveries",
    )
    op.drop_index("ix_notification_deliveries_template_id", table_name="notification_deliveries")
    op.drop_index("ix_notification_deliveries_rule_id", table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_index("ix_inbound_events_workspace_status_received", table_name="inbound_events")
    op.drop_index("ix_inbound_events_channel_connection_id", table_name="inbound_events")
    op.drop_table("inbound_events")
    op.drop_index("ix_form_submissions_workspace_status_created", table_name="form_submissions")
    op.drop_index("ix_form_submissions_form_id", table_name="form_submissions")
    op.drop_table("form_submissions")
    op.drop_index(op.f("ix_form_rate_limit_buckets_form_id"), table_name="form_rate_limit_buckets")
    op.drop_index("ix_form_rate_bucket_workspace_id", table_name="form_rate_limit_buckets")
    op.drop_index("ix_form_rate_bucket_expires", table_name="form_rate_limit_buckets")
    op.drop_table("form_rate_limit_buckets")
    op.drop_index("ix_external_identities_contact_id", table_name="external_identities")
    op.drop_index("ix_external_identities_channel_connection_id", table_name="external_identities")
    op.drop_table("external_identities")
    op.drop_index("ix_conversations_workspace_status_updated", table_name="conversations")
    op.drop_index("ix_conversations_deal_id", table_name="conversations")
    op.drop_index("ix_conversations_contact_id", table_name="conversations")
    op.drop_index("ix_conversations_channel_connection_id", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_webhook_endpoints_stage_id", table_name="webhook_endpoints")
    op.drop_index("ix_webhook_endpoints_source_id", table_name="webhook_endpoints")
    op.drop_index("ix_webhook_endpoints_slug_active", table_name="webhook_endpoints")
    op.drop_index("ix_webhook_endpoints_pipeline_id", table_name="webhook_endpoints")
    op.drop_index("ix_webhook_endpoints_assignee_id", table_name="webhook_endpoints")
    op.drop_table("webhook_endpoints")
    op.drop_index("ix_notification_rules_workspace_event_enabled", table_name="notification_rules")
    op.drop_index("ix_notification_rules_template_id", table_name="notification_rules")
    op.drop_index("ix_notification_rules_stage_id", table_name="notification_rules")
    op.drop_index("ix_notification_rules_source_id", table_name="notification_rules")
    op.drop_index("ix_notification_rules_pipeline_id", table_name="notification_rules")
    op.drop_table("notification_rules")
    op.drop_index("ix_forms_stage_id", table_name="forms")
    op.drop_index("ix_forms_source_id", table_name="forms")
    op.drop_index("ix_forms_slug_active", table_name="forms")
    op.drop_index("ix_forms_pipeline_id", table_name="forms")
    op.drop_index("ix_forms_assignee_id", table_name="forms")
    op.drop_table("forms")
    op.drop_index("ix_contact_points_workspace_kind_normalized", table_name="contact_points")
    op.drop_index("ix_contact_points_contact_id", table_name="contact_points")
    op.drop_table("contact_points")
    op.drop_index("ix_contact_consents_workspace_status", table_name="contact_channel_consents")
    op.drop_index("ix_contact_consents_contact_id", table_name="contact_channel_consents")
    op.drop_table("contact_channel_consents")
    op.drop_index("ix_channel_connections_workspace_kind_status", table_name="channel_connections")
    op.drop_index("ix_channel_connections_default_stage_id", table_name="channel_connections")
    op.drop_index("ix_channel_connections_default_pipeline_id", table_name="channel_connections")
    op.drop_index("ix_channel_connections_default_assignee_id", table_name="channel_connections")
    op.drop_table("channel_connections")
    op.drop_index("ix_external_entity_maps_internal", table_name="external_entity_maps")
    op.drop_index("ix_external_entity_maps_import_job_id", table_name="external_entity_maps")
    op.drop_table("external_entity_maps")
    op.drop_index(
        op.f("ix_notification_templates_workspace_id"), table_name="notification_templates"
    )
    op.drop_table("notification_templates")
    op.drop_index("ix_import_jobs_workspace_status_updated", table_name="import_jobs")
    op.drop_table("import_jobs")
    op.drop_index(
        "ix_amocrm_oauth_states_workspace_expiry", table_name="amocrm_oauth_states"
    )
    op.drop_index(
        "ix_amocrm_oauth_states_initiated_by_id", table_name="amocrm_oauth_states"
    )
    op.drop_table("amocrm_oauth_states")
    op.drop_index("ix_amocrm_connections_account_domain", table_name="amocrm_connections")
    op.drop_table("amocrm_connections")
    # ### end Alembic commands ###
